#!bin/bash script


#Ubuntu 16 update and upgrade

sudo apt-get install update -y
sudo apt-get upgrade -y
#####################################################################

# Create New User Stack & add to Sudors
sudo -i
adduser stack
echo "stack ALL=(ALL) NOPASSWD :ALL" >> /etc/sudoers
exit
###################################################################

#Download Devstack from github 
sudo apt-get install -y git 
sudo git clone https://github.com/omarabdalhamid/devstack.git

####################################################################

#Avoiding eroors
sudo rm /var/lib/dpkg/lock
sudo rm /var/lib/apt/lists/lock
sudo rm /var/lib/apt/archives/lock
sudo rm -rf /var/lib/lists/*

#####################################################################

#Run stack Script

sudo sh /devstack/stack.sh
